---
title: "Exploratory Analysis to Survival data"
author: "Wenjun He"
date: "October 31, 2020 (Version 2)"
output:
  html_notebook:
    toc: yes
---

# Background

Doing the exploratory analysis for a survival data. Data (*training-1(20201011).xlsx*) was provided by Dr. Jiaxing LU. In this analysis, we will doing the three main parts:

- Data preprocessing
- Statistical descriptive analysis
- Univariable analysis
- Mutivariable analysis including LASSO

<br>

# Step 1 - Data preprocessing

```{r,echo=TRUE, warning=FALSE, message=FALSE}
library("readxl")
setwd("/hewenjun/rstudio_work/zhenweipeng")
st1 <- read_excel("training-1(20201011).xlsx")

for (j in colnames(st1)) {
  st1[,j] <- as.numeric(as.matrix(st1[,j]))
}
for (k in 1:length(colnames(st1))){
  colnames(st1)[k] <- gsub("-", "_", colnames(st1)[k])
  colnames(st1)[k] <- gsub("\\...", "col", colnames(st1)[k])
}

data_OS <- st1[,-(3:4)]
data_RFS <- st1[,-c(1:2)]
```

# Step2 
```{r,echo=FALSE, warning=FALSE, message=FALSE}
setwd("/hewenjun/rstudio_work/survival_example")
source("/hewenjun/rstudio_work/DataAnalysis/SurvivalAnalysis/surv_describe.R")
source("/hewenjun/rstudio_work/DataAnalysis/SurvivalAnalysis/surv_univar.R")
```

```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(cowplot)
library(reshape2)
library(pheatmap)

outcome_var <- c("OS","Death")
surv_describe_res <- surv_describe(data_frame = data_OS, outcome_var = outcome_var)
```

# Step3 
```{r,echo=FALSE, warning=FALSE, message=FALSE}
source("/hewenjun/rstudio_work/SurvivalAnalysis/surv_univar.R")
surv_univar_res <- surv_univar(surv_describe_res[[1]], outcome_var, surv_describe_res[8],surv_describe_res[9])

jpeg(file = paste(outcome_var[2], "survival_KM.jpeg", sep = "_"), width = 2100, height = 1500)
surv_univar_res[3]
while (!is.null(dev.list()))  dev.off()
```



```{r,echo=FALSE, warning=FALSE, message=FALSE}
outcome_var <- c("RFS","Recurrence")
surv_describe_res <- surv_describe(data_frame = data_RFS, outcome_var = outcome_var)

# Pic1
jpeg(file = paste(outcome_var[2], "continus_variable_distribution.jpg", sep = "_"), width = 10000, height = 10000)
surv_describe_res[4]
while (!is.null(dev.list()))  dev.off()

# Pic2
jpeg(file = paste(outcome_var[2], "continus_variable_boxplot.jpg", sep = "_"), width = 2000, height = 1000)
surv_describe_res[5]
while (!is.null(dev.list()))  dev.off()

# Pic3
jpeg(file = paste(outcome_var[2], "correlation_map.jpg", sep = "_"), width = 1000, height = 1000)
surv_describe_res[6]
while (!is.null(dev.list()))  dev.off()

# Pic4
jpeg(file = paste(outcome_var[2], "categorical_variable_barplot.jpg", sep = "_"), width = 10000, height = 10000)
surv_describe_res[7]
while (!is.null(dev.list()))  dev.off()
```

